# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'gradle'

    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

    - name: Restore gradle.properties
      env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
        echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

    - name: Make secrets folder
      run: |
          mkdir ./secrets
      shell: bash
  
    - name: Write certificate to file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'cert.p7b'
        fileDir: './secrets'
        encodedString: ${{ secrets.CERT }}

    - name: Write keystore to file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'keystore.jks'
        fileDir: './secrets'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew buildAll

    - name: Upload Modules as Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./modules/example-perspective-component/build/ExamplePerspectiveComponent.modl
        asset_name: PerspectiveComponentExample.modl
        tag: ${{ github.ref }}
        overwrite: true
        body: "Hey, maybe this is working?"


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
