# GitHub Actions workflow to publish new releases.
name: 'Publish releases'
on: 
  workflow_dispatch:
  push:
    tags:
    - '*'

env:
  JAVA_VERSION: 21
  NODE_VERSION: 20

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  github:
    name: 'Release on GitHub'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      version: '${{ steps.version.outputs.version }}'
    steps:
      - name: 'Publish new versions'
        id: publish
        run: ./gradlew githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Java ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'zulu'

      - name: 'Fetch git tags' # Required for axion-release-plugin
        run: git fetch --tags --unshallow

      - name: 'Make gradlew executable'
        run: chmod +x ./gradlew

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
